# Copyright 2026 SECO Mind Srl
# SPDX-License-Identifier: Apache-2.0

name: docker

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Build docker images
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6
      - name: Build Docker image
        run: docker build .
